spring:
  application:
    name: OrderManager
  jpa:
    #generate-ddl: true
    #hibernate:
    #  ddl-auto: update
    show-sql: true
    generate-ddl: false
  datasource:
    url: jdbc:mysql://localhost:3306/oms?useSSL=false
    username: root
    password:
endpoints:
  flyway:
    sensitive: false
flyway:
  locations: sql
management:
  cloudfoundry:
    skip-ssl-validation: true
  security:
    enabled: false
        
security:
  basic:
    enabled: false

logging:
  level:
    io:
      pivotal:
        om: DEBUG
config:
  rate: 1
